apiVersion: v1
kind: Pod
metadata:
  name: vault
spec:
  containers:
  - name: vault
    image: vault
    command: ['vault','server','-dev','-log-level','debug','-dev-listen-address','0.0.0.0:8200']
    resources: {}
    ports:
    - containerPort: 8200
