apiVersion: v1
kind: Pod
metadata:
  name: helloapp-1
  labels:
    app: helloapp
    ver: v1
spec:
  containers:
  - name: helloapp-1
    image: poznajkubernetes/helloapp:svc
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: helloapp2
  labels:
    app: helloapp
    ver: v2
spec:
  containers:
  - name: helloapp-2
    image: poznajkubernetes/helloapp:svc
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
