apiVersion: v1
kind: Pod
metadata:
  name: pkad
spec:
  restartPolicy: Never
  containers:
  - name: pkad
    image: poznajkubernetes/pkad
    env:
    - name: MY_NAME
      value: "Sebastian"
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    envFrom:
      - configMapRef:
          name: cm01-mod03-cw2       
    resources: {}