apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox:1
    name: busybox
    resources: {}
    command:
      - sleep
      - "10"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
